name = "VectorTransformer"
uuid = "c8e6c799-df3e-4af8-b563-7df566ea393d"
authors = ["Stephen Prior <stephen@prior.technology> and contributors"]
version = "0.1.0-DEV"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
